export const ALUMINI_LIST_REQUEST = 'ALUMINI_LIST_REQUEST'
export const ALUMINI_LIST_SUCCESS = 'ALUMINI_LIST_SUCCESS'
export const ALUMINI_LIST_FAIL = 'ALUMINI_LIST_FAIL'

export const ALUMINI_CREATE_SUCCESS = 'ALUMINI_CREATE_SUCCESS'
export const ALUMINI_CREATE_REQUEST = 'ALUMINI_CREATE_REQUEST'
export const ALUMINI_CREATE_FAIL = 'ALUMINI_CREATE_FAIL'
export const ALUMINI_CREATE_RESET = 'ALUMINI_CREATE_RESET'

export const ALUMINI_DELETE_SUCCESS = 'ALUMINI_DELETE_SUCCESS'
export const ALUMINI_DELETE_REQUEST = 'ALUMINI_DELETE_REQUEST'
export const ALUMINI_DELETE_FAIL = 'ALUMINI_DELETE_FAIL'

export const ALUMINI_UPDATE_REQUEST = 'ALUMINI_UPDATE_REQUEST'
export const ALUMINI_UPDATE_SUCCESS = 'ALUMINI_UPDATE_SUCCESS'
export const ALUMINI_UPDATE_FAIL = 'ALUMINI_UPDATE_FAIL'
export const ALUMINI_UPDATE_RESET = 'ALUMINI_UPDATE_RESET'

export const ALUMINI_DETAIL_REQUEST = 'ALUMINI_DETAIL_REQUEST'
export const ALUMINI_DETAIL_SUCCESS = 'ALUMINI_DETAIL_SUCCESS'
export const ALUMINI_DETAIL_FAIL = 'ALUMINI_DETAIL_FAIL'
