export const ALUMINI_LIST_REQUEST = 'ALUMINI_LIST_REQUEST'
export const ALUMINI_LIST_SUCCESS = 'ALUMINI_LIST_SUCCESS'
export const ALUMINI_LIST_FAIL = 'ALUMINI_LIST_FAIL'

export const ALUMINI_DETAIL_REQUEST = 'ALUMINI_DETAIL_REQUEST'
export const ALUMINI_DETAIL_SUCCESS = 'ALUMINI_DETAIL_SUCCESS'
export const ALUMINI_DETAIL_FAIL = 'ALUMINI_DETAIL_FAIL'
export const ALUMINI_DETAIL_RESET = 'ALUMINI_DETAIL_RESET'
