export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST'
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS'
export const USER_DETAIL_FAIL = 'USER_DETAIL_FAIL'
export const USER_DETAIL_RESET = 'USER_DETAIL_RESET'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const EMAIL_OTP_REQUEST = 'EMAIL_OTP_REQUEST'
export const EMAIL_OTP_SUCCESS = 'EMAIL_OTP_SUCCESS'
export const EMAIL_OTP_FAIL = 'EMAIL_OTP_FAIL'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_REFRESH = 'USER_UPDATE_REFRESH'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'

export const FOLLOW_ADD_REQUEST = 'FOLLOW_ADD_REQUEST'
export const FOLLOW_ADD_SUCCESS = 'FOLLOW_ADD_SUCCESS'
export const FOLLOW_ADD_FAIL = 'FOLLOW_ADD_FAIL'

export const ADD_TIP_REQUEST = 'ADD_TIP_REQUEST'
export const ADD_TIP_SUCCESS = 'ADD_TIP_SUCCESS'
export const ADD_TIP_FAIL = 'ADD_TIP_FAIL'
export const ADD_TIP_RESET = 'ADD_TIP_RESET'

export const ADD_LINK_REQUEST = 'LINK_TIP_REQUEST'
export const ADD_LINK_SUCCESS = 'LINK_TIP_SUCCESS'
export const ADD_LINK_FAIL = 'ADD_LINK_FAIL'
export const ADD_LINK_RESET = 'ADD_LINK_RESET'

export const USER_TIP_LINK_REQUEST = 'USER_TIP_LINK_REQUEST'
export const USER_TIP_LINK_SUCCESS = 'USER_TIP_LINK_SUCCESS'
export const USER_TIP_LINK_FAIL = 'USER_TIP_LINK_FAIL'
export const USER_TIP_LINK_RESET = 'USER_TIP_LINK_RESET'
