export const PROF_LIST_REQUEST = 'PROF_LIST_REQUEST'
export const PROF_LIST_SUCCESS = 'PROF_LIST_SUCCESS'
export const PROF_LIST_FAIL = 'PROF_LIST_FAIL'

export const PROF_CREATE_SUCCESS = 'PROF_CREATE_SUCCESS'
export const PROF_CREATE_REQUEST = 'PROF_CREATE_REQUEST'
export const PROF_CREATE_FAIL = 'PROF_CREATE_FAIL'
export const PROF_CREATE_RESET = 'PROF_CREATE_RESET'