export const PROF_LIST_REQUEST = 'PROF_LIST_REQUEST'
export const PROF_LIST_SUCCESS = 'PROF_LIST_SUCCESS'
export const PROF_LIST_FAIL = 'PROF_LIST_FAIL'

export const PROF_CREATE_SUCCESS = 'PROF_CREATE_SUCCESS'
export const PROF_CREATE_REQUEST = 'PROF_CREATE_REQUEST'
export const PROF_CREATE_FAIL = 'PROF_CREATE_FAIL'
export const PROF_CREATE_RESET = 'PROF_CREATE_RESET'

export const PROF_DELETE_SUCCESS = 'PROF_DELETE_SUCCESS'
export const PROF_DELETE_REQUEST = 'PROF_DELETE_REQUEST'
export const PROF_DELETE_FAIL = 'PROF_DELETE_FAIL'

export const PROF_UPDATE_REQUEST = 'PROF_UPDATE_REQUEST'
export const PROF_UPDATE_SUCCESS = 'PROF_UPDATE_SUCCESS'
export const PROF_UPDATE_FAIL = 'PROF_UPDATE_FAIL'
export const PROF_UPDATE_RESET = 'PROF_UPDATE_RESET'

export const PROF_DETAIL_REQUEST = 'PROF_DETAIL_REQUEST'
export const PROF_DETAIL_SUCCESS = 'PROF_DETAIL_SUCCESS'
export const PROF_DETAIL_FAIL = 'PROF_DETAIL_FAIL'
